"""
Django settings for myshop project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os

from pathlib import Path
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-u9j#219*@rss2)l(#$a0#qp2-9-ya6ylcsv19@bkyv-ytae7)('

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'shop.apps.ShopConfig',
    'cart.apps.CartConfig',
    'orders.apps.OrdersConfig',
    'payment.apps.PaymentConfig',
    'coupons',
    'rosetta',
    'parler',
    'localflavor',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # Middleware de localización
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myshop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',  # Añadido para archivos media
                'cart.context_processors.cart',
            ],
        },
    },
]

WSGI_APPLICATION = 'myshop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
CART_SESSION_ID = 'cart'

# Internationalization
LANGUAGE_CODE = 'en'

LANGUAGES = (
('en', 'English'),
('es', 'Spanish',)
)

LOCALE_PATHS = (
    os.path.join(BASE_DIR, 'locale/'),
    os.path.join(BASE_DIR, 'orders', 'locale'), # Específico de orders
)

TIME_ZONE = 'UTC'
USE_I18N = True
# settings.py
USE_L10N = True  # Desactiva la localización de formatos
USE_THOUSAND_SEPARATOR = False  # Evita separadores de miles
DECIMAL_SEPARATOR = '.'  # Fuerza punto decimal
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

# Estos son solo para desarrollo: dónde buscar archivos estáticos personalizados
STATICFILES_DIRS = [
    
    BASE_DIR / 'static',       # Otra carpeta general "static" en tu proyecto
]

# Esta es la carpeta donde Django reunirá TODOS los archivos estáticos cuando hagas collectstatic
STATIC_ROOT = BASE_DIR / 'staticfiles'


# Media files (Imágenes subidas por usuarios)
MEDIA_URL = '/media/'  # URL para acceder a los archivos
MEDIA_ROOT = BASE_DIR / 'media'  # Ruta donde se guardan físicamente

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email backend para desarrollo: muestra correos en consola
#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
# Solo para desarrollo (en producción cambia esto)
if DEBUG:
    # Permite ver emails en consola durante desarrollo
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    # Configuración real para producción
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'



# Configuración Braintree
BRAINTREE_MERCHANT_ID = 'xgzj9gg92tkkv2d4'  # Reemplazar con tu Merchant ID
BRAINTREE_PUBLIC_KEY = 'qzfr98py32d2z5vx'   # Reemplazar con tu Public Key
BRAINTREE_PRIVATE_KEY = 'c60456c9747c818783d874ea146a2b7b'  # Reemplazar con tu Private Key


from braintree import Configuration, Environment

Configuration.configure(
    Environment.Sandbox,
    BRAINTREE_MERCHANT_ID,
    BRAINTREE_PUBLIC_KEY,
    BRAINTREE_PRIVATE_KEY,
    
)

PARLER_LANGUAGES = {
    None: (
        {'code': 'en'},  # Inglés
        {'code': 'es'},  # Español
    ),
    'default': {
        'fallback': 'en',  # Idioma de respaldo
        'hide_untranslated': False,  # Mostrar contenido no traducido
    }
}
# Configuración específica para parler
PARLER_DEFAULT_LANGUAGE_CODE = 'en'
PARLER_SHOW_EXCLUDED_LANGUAGE_TABS = True

REDIS_HOST = 'localhost'
REDIS_PORT = 6379
REDIS_DB = 1

# Configuración Celery
CELERY_BROKER_URL = 'redis://localhost:6379/0'  # O tu URL de RabbitMQ
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'